### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by hery** [fukamachi/caveman#106]
Hi there! Nice work on your framework!

Question, I need to add auth to my web app.
As far as I've searched and understood, there's isn't any implementation or integration in Caveman yet.

Would the simplest solution be to implement it myself? 
Which I'm guessing would include password hashing and session handling, right?
Although I've seen sessions are already supported, so I'd only need to integrate whatever I implement with that, right?

Would you be interested in having that integrated into your framework at some point? 
i.e. a PR we could merge when ready.

Thanks!

**Comment by fukamachi** [comment]
Thank you for your interests.

I'm afraid that there's no provided way about authentication in Caveman2 since it aims to be lightweight.
[Mito](https://github.com/fukamachi/mito) and [Mito-Auth](https://github.com/fukamachi/mito-auth) would help you.
