### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/caveman#127]
Building with SBCL 2.1.6 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id f6ae0fe20bca5ba75a8bc5dcaea8cf59f12c2da5

*caveman-middleware-dbimanager* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A18103}>: Component "clack-v1-compat" not found, required by #<SYSTEM "caveman-middleware-dbimanager">

```

*caveman-test* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A18103}>: Component "clack-v1-compat" not found, required by #<SYSTEM "caveman">

```

*caveman2-db* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A18103}>: Component "clack-v1-compat" not found, required by #<SYSTEM "caveman-middleware-dbimanager">

```

*caveman* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A18103}>: Component "clack-v1-compat" not found, required by #<SYSTEM "caveman">

```

[Full log here](http://report.quicklisp.org/2021-07-06/failure-report/caveman.html)

**Comment by fukamachi** [comment]
Thank you for the report.
I deleted code depending on clack-v1-compat.
It should be fixed now.
