### ISSUE TITLE
Need an utility function for getting param values from _parsed

### ISSUE THREAD

**Issue by rajasegar** [fukamachi/caveman#129]
As mentioned in the README we are picking the POST parameter values from the `_parsed` like this:

```lisp
(defroute "/edit" (&key _parsed)
  (format nil "~S" (cdr (assoc "person" _parsed :test #'string=))))
```

I think this is a recurring pattern and if we have an inbuilt utility function as part of Caveman something like:
```lisp
(defun get-param (name parsed)
  (cdr (assoc name parsed :test #'string=)))
```
We can use this with something like:
```lisp
(defroute "/edit" (&key _parsed)
  (format nil "~S" (get-param "person" _parsed)))
```
That would be super useful.

Reddit discussion:
https://www.reddit.com/r/lisp/comments/on9hs2/built_a_small_trello_clone_demo_app_in_common_lisp/h5qce0b?utm_source=share&utm_medium=web2x&context=3

@fukamachi Please let us know your thoughts...

**Comment by asarch** [comment]
I use this:

```Lisp
(defun parametro (elemento lista)
  (format t "Procesando: ~s~%" lista)
  (cdr (assoc elemento lista :test #'string=)))
```

and then:
```Lisp
(defroute ("/notas/agregar" :method :POST) (&key _parsed)
  (with-connection
      (db :agenda)
    (execute
     (insert-into :nota
		  (set=
		   :nombre (parametro "nombre" _parsed)
		   :descripcion (parametro "descripcion" _parsed)
		   :contenido (remove #\return (parametro "contenido" _parsed))
		   :tipo (parametro "tipo" _parsed)))))
  (redirect "/notas"))
```

**Comment by vindarel** [comment]
Hi everyone, was a utility function merged? (or assoc-utils added to the requirements ?) I agree it would be nice to have something ready to use. 

I still see the use of `(cdr (assoc … _parsed` in the README.

**Comment by fukamachi** [comment]
No changes to this issue yet.
While I recommend using assoc-utils, code samples in README may be better to be changed.
