### ISSUE TITLE
Compilation error after system update

### ISSUE THREAD

**Issue by foggynight** [fukamachi/caveman#134]
Hello,

Last night I performed a system update (Arch Linux), and as of this morning, when I quickload my caveman2 project I get a `COMPILE-FILE-ERROR` with the following message:

```
COMPILE-FILE-ERROR while
compiling #<CL-SOURCE-FILE "static-vectors" "impl">
```

I'm able to `ACCEPT` and then just carry on, the webserver works from there, but this error concerns me, anyone else with this issue or who knows of a fix?

Thanks,
foggynight

**Comment by fukamachi** [comment]
Can't say anything about reports with no backtrace logs for sure, but #126 may help.
If not, paste the backtrace that follows the error message, please.

**Comment by foggynight** [comment]
Your diagnosis in #126 applied to me as well, cloning the upstream `static-vectors` repo into my `quicklisp/local-projects` directory fixed the issue, thanks!
