### ISSUE TITLE
10 second fix: Please enable the Wiki

### ISSUE THREAD

**Issue by daninus14** [fukamachi/caveman#143]
Please enable the wiki for anyone to add information

This project is great! Thank you!

however, it is terribly lacking documentation. By enabling the wiki anyone can contribute without a PR, and there are tons of things that should be added, like for example: [dealing with cookies](https://github.com/fukamachi/ningle/issues/43)

Thanks

**Comment by fukamachi** [comment]
Okay, there's no reason to reject such an easy task.

**Comment by daninus14** [comment]
Thanks!
