### ISSUE TITLE
Low cohesion between CLSQL and CL-EMB

### ISSUE THREAD

**Issue by vityok** [fukamachi/caveman#20]
A simple CLSQL:SELECT on all entries in a table returns a list of CLOS objects, something like:

```
((#<OBJ {123}>) (#<OBJ {124}>))
```

But CL-EMB, especially in a loop, expects to see a list of plist-s, not this list of instances. I guess that it would nice to either have some sort of a convertor function from objects to plists or CL-EMB to accept objects along with plists.

**Comment by vindarel** [comment]
Hello maintainer, this one can be closed, Caveman uses Djula now.
