### ISSUE TITLE
Readme needs some additional notes

### ISSUE THREAD

**Issue by upwardindex** [fukamachi/caveman#4]
If you follow the steps to create a skeleton project and try to run it, you encounter two problems.
1. cffi/uffi-compat fails to compile. That is because the version in quicklisp is too old.
2. libsqlite3 fails to load. 

I suggest that you add two notes. A note mentionning that you should have libsqlite3-dev installed and another note mentionning that people should clone cffi git repo directly to have the lastest version.

With these two changes, everything works well.

**Comment by vindarel** [comment]
that's old, close?
