### ISSUE TITLE
Documentation issue in templates/cl-emb section

### ISSUE THREAD

**Issue by ghost** [fukamachi/caveman#48]
The documentation references calling #'render as follows:

```lisp
(render #P"something.tmpl"
  :template-variable "template-value")
```

Unfortunately, at least on my Quicklisp install of caveman2/cl-emb, this does not work, you have to pass the template variables as a list in the ':env' slot (optional parameter to #'render).

The correct call is:
```lisp
(render #P"something.tmpl"
  '(:template-variable "template-value"))
```

This threw me for a small loop when first setting up (thanks slime for making it so easy to fix though!)

**Comment by blasut** [comment]
I'm having trouble getting stuff from a database and sending it to the template.

Would be nice to have an example of that. Like:

```
(render #P"something.tmpl"
  '(:list-of-things (get-things-from-db))
