### ISSUE TITLE
Document starting an application

### ISSUE THREAD

**Issue by anthonyshull** [fukamachi/caveman#50]
I can't figure out how to start an application after creating it. If I run:

    %> (ql:quickload :caveman2)
    %> (caveman2:make-project ...)

I can then run:

    %> (ql:quickload :project-name)
    %> (project-name:start :port 8080)

But, if I exit the REPL, I have no idea how to re-start the application. My guess is that make-project returns a reference to the project which allows me to load it. If that process could be added to the documentation, it would help me (and other people wanting to play with caveman) out.

**Comment by kennymalac** [comment]
Was wondering how to get going and started as well

**Comment by fukamachi** [comment]
See http://www.quicklisp.org/beta/faq.html#local-project.

**Comment by anthonyshull** [comment]
Thanks!
