### ISSUE TITLE
Update to README

### ISSUE THREAD

**Issue by deusmax** [fukamachi/caveman#55]
Made some updates to the README file for caveman2.

The goal is to make it easier for a new person looking into caveman to follow through with the Quick-start and the examples. The idea is to create a "myapp" project that one can use to try-out the examples provided in the README. For this, an  **example** directory is used for the sample files.

All one has to do to try the examples is: 
1. follow the quick-start
2. create a new project "myapp"
3. copy the files from the example directory to their respective place
4. set-up the database connections
5. point your browser to try out the examples.

Feel free to use any of these, if you find them useful.
I will upload the README-caveman.markdown and example.tar.gz files as soon as I figure out how.

Hope this helps

**Comment by vindarel** [comment]
Hello, it seems that issue can be closed.
