### ISSUE TITLE
why was cl-emb replaced with djula? should it be an option go make-project?

### ISSUE THREAD

**Issue by ahungry** [fukamachi/caveman#58]
I did a caveman2 site about half a year ago and it used cl-emb including custom view.lisp functions for rendering it on project generation.

I started a new one last night and see the tempting engine was changed.

What does djula offer over cl-emb?

**Comment by ahungry** [comment]
Excuse the typos, on mobile.  Tempting = templating, darn auto correct. 

Also as title says, maybe template engine could be passed to make-project call.

**Comment by fukamachi** [comment]
Because Djula is more promising than CL-EMB.
It has modern features like template inheritance and is maintained by an active developer.
Any problems with it?

**Comment by ahungry** [comment]
No problems, its good so far. A little bummed I spent an evening adding cl-emb compatability to emacs web-mode plug in awhile ago though! :)

-------- Original message --------

**Comment by chuchana** [comment]
The `see also` section on [8arrow.org/caveman](http://8arrow.org/caveman/) still mentions `cl-emb` instead of `djula`

**Comment by vindarel** [comment]
The index was updated, this one can be closed.
