### ISSUE TITLE
What's the right way to use lack.middleware.session.store?

### ISSUE THREAD

**Issue by jackcarrozzo** [fukamachi/caveman#65]
What's the right way to interact with sessions in v2? My code is doing things like this, originally written before lack:

````(gethash :userid *session*)````

However, ```*session*``` is now nil after updating caveman and deps. I poked around a while in ````lack/src/middleware/session/````, but its not immediately clear to me what is the intended use of the class and methods. Is there a way to access a particular session's hashtable directly?

Thanks!

**Comment by fukamachi** [comment]
I think the way to use sessions wasn't changed since v1.
Could you show me your `lack:builder` expression in your app.lisp? I'd like to see if `:session` is enabled in it.

```common-lisp
(builder
  :session
  *web*)
```

**Comment by jackcarrozzo** [comment]
Sure, here's what I've got:

````
(builder
 (:static
  :path (lambda (path)
          (if (ppcre:scan
               "^(?:/font.*|.*\\.(txt|css|js)$)"
               path)
              path
              nil))
  :root *static-directory*)
 (if (productionp)
     nil
     :accesslog)
 (if (getf (config) :error-log)
     '(:backtrace
       ;;:output (getf (config) :error-log))
       :output t)
     nil)
 :session
 (if (productionp)
     nil
     (lambda (app)
       (lambda (env)
         (let ((datafly:*trace-sql* t))
           (funcall app env)))))
 *web*)
````

Here's the func that's trying to use the session:

````
(defun get-session-userid (&key (throw-code T))
  (format t "*session*: ~A~%" *session*)

  (or
   (gethash :userid *session*)
   (if throw-code
       (throw-code 403))))
````

Running the above produces this (in src/web.lisp, called from a route):

````
*session*: NIL
Backtrace for: #<SB-THREAD:THREAD "hunchentoot-worker-127.0.0.1:53152" RUNNING {1009DE3FF3}>
0:  [tl,external]
1: 
[...]
31: 
Above backtrace due to this condition:
The value NIL is not of type HASH-TABLE.
````

**Comment by fukamachi** [comment]
Ah, I think it's a bug in ningle which was reported at https://github.com/fukamachi/ningle/issues/9.
Unfortunately, the fixed version is not included in Quicklisp dist yet, so you have to "git clone" the latest ningle to try it (or just waiting for the next dist release may be acceptable as I expect it will be released soon).

**Comment by jackcarrozzo** [comment]
Ahhhhh yep, that was it - using the latest ningle fixed it.

Thanks!!
