### ISSUE TITLE
Redirect?

### ISSUE THREAD

**Issue by sabracrolleton** [fukamachi/caveman#77]
I can't seem to get redirect to work. 

Base case, assume a login form passes the parameters to (defroute ("/validate-password" :method :POST) (&key _parsed) 

The password gets validated and then the user should be redirected to "/".

If I just render index.html, the url showing at the top of the browser will still be "/validate-password".

What am I missing?

**Comment by aarvid** [comment]
```lisp
(caveman2.helper:redirect "/")
```

or

```lisp
(caveman2:redirect "/")
```

**Comment by sabracrolleton** [comment]
Wierd. Working Now. Did not work last week. Obviously something wrong with my configuration and not caveman.
