### ISSUE TITLE
Set cookies.

### ISSUE THREAD

**Issue by rlisper** [fukamachi/caveman#91]
Sorry, maybe an obvious question, but what is properly way to set cookies in caveman2? I try to set (request-cookies *request*) in the defroute macro but it doesn't work for me.

**Comment by knobo** [comment]
I don't know, but I do:

``` cl
(defun make-cookie (name &key value path domain secure httponly expires)
  (setf (getf (caveman2:response-set-cookies *response*) name)
	(list :value value
	      :domain domain
	      :expires expires
	      :secure secure
	      :path path
	      :httponly httponly)))
```

`request-cookies` is for reading cookies not setting
